import { DocumentInfo } from '@/types';
import { LayerCompositor } from '@/utils/layerCompositor';
import * as bridge from '@/services/tauriBridge';
import { save } from '@tauri-apps/plugin-dialog';
import { writeFile } from '@tauri-apps/plugin-fs';
import { canvasToBlob, canvasToPdfBlob, canvasToTiffBlob } from './rasterEncoders';
export { canvasToPdfBlob } from './rasterEncoders';

export type ExportFormat =
  'png' | 'jpeg' | 'webp' | 'bmp' | 'tiff' | 'svg' | 'pdf' | 'cdraw' | 'psd';

export interface ExportOptions {
  format: ExportFormat;
  quality?: number; // 0.1 to 1.0
  transparentBg?: boolean;
}

/**
 * Accurately composites all visible layers in stack order (bottom to top)
 * respecting per-layer opacity and CSS mix-blend-modes.
 */
export const compositeVisibleLayersToCanvas = (
  doc: DocumentInfo,
  transparentBg = false,
  maxDimension?: number
): HTMLCanvasElement => {
  const exportCanvas = document.createElement('canvas');
  const scale = maxDimension ? Math.min(1, maxDimension / Math.max(doc.width, doc.height)) : 1;
  exportCanvas.width = Math.max(1, Math.round(doc.width * scale));
  exportCanvas.height = Math.max(1, Math.round(doc.height * scale));
  const compositor = new LayerCompositor();
  try {
    compositor.render(
      exportCanvas,
      doc,
      (id) => document.getElementById(`layer-canvas-${id}`) as HTMLCanvasElement | null,
      undefined,
      { whiteBackground: !transparentBg }
    );
  } finally {
    compositor.dispose();
  }

  return exportCanvas;
};

/**
 * Generate 24-bit uncompressed Windows BMP file bytes from an HTMLCanvasElement
 */
export const canvasToBmpBlob = (canvas: HTMLCanvasElement): Blob => {
  const width = canvas.width;
  const height = canvas.height;
  const ctx = canvas.getContext('2d');
  const imgData = ctx ? ctx.getImageData(0, 0, width, height) : null;
  const data = imgData ? imgData.data : new Uint8Array(width * height * 4);

  const rowSize = Math.floor((24 * width + 31) / 32) * 4;
  const pixelArraySize = rowSize * height;
  const fileSize = 54 + pixelArraySize;

  const buffer = new ArrayBuffer(fileSize);
  const view = new DataView(buffer);

  // BMP Header (14 bytes)
  view.setUint16(0, 0x4d42, true); // 'BM'
  view.setUint32(2, fileSize, true);
  view.setUint16(6, 0, true);
  view.setUint16(8, 0, true);
  view.setUint32(10, 54, true); // Pixel array offset

  // DIB Header (BITMAPINFOHEADER - 40 bytes)
  view.setUint32(14, 40, true);
  view.setInt32(18, width, true);
  view.setInt32(22, height, true); // Bottom-up
  view.setUint16(26, 1, true); // Color planes
  view.setUint16(28, 24, true); // Bits per pixel
  view.setUint32(30, 0, true); // BI_RGB (no compression)
  view.setUint32(34, pixelArraySize, true);
  view.setInt32(38, 2835, true); // ~72 DPI horizontal
  view.setInt32(42, 2835, true); // ~72 DPI vertical
  view.setUint32(46, 0, true);
  view.setUint32(50, 0, true);

  const pixelBytes = new Uint8Array(buffer, 54, pixelArraySize);
  for (let y = 0; y < height; y++) {
    const srcRow = height - 1 - y; // Bottom-up
    const rowOffset = y * rowSize;
    for (let x = 0; x < width; x++) {
      const srcIdx = (srcRow * width + x) * 4;
      const dstIdx = rowOffset + x * 3;
      pixelBytes[dstIdx] = data[srcIdx + 2]; // B
      pixelBytes[dstIdx + 1] = data[srcIdx + 1]; // G
      pixelBytes[dstIdx + 2] = data[srcIdx]; // R
    }
  }

  return new Blob([buffer], { type: 'image/bmp' });
};

/**
 * Generate standard SVG container embedding high-resolution composited bitmap
 */
export const canvasToSvgString = (canvas: HTMLCanvasElement, docTitle: string): string => {
  const dataUrl = canvas.toDataURL('image/png');
  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${canvas.width}" height="${canvas.height}" viewBox="0 0 ${canvas.width} ${canvas.height}">
  <title>${(docTitle || 'CekcokDraw Artwork').replace(/[<>&"']/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;', "'": '&apos;' })[c]!)}</title>
  <desc>Generated by CekcokDraw Raster Graphics Studio</desc>
  <image width="${canvas.width}" height="${canvas.height}" xlink:href="${dataUrl}" />
</svg>`;
};

/**
 * Export full multi-layer project package (.cdraw) with layer metadata & pixel data URLs
 */
export const exportCekcokProject = (doc: DocumentInfo): Blob => {
  const layerData: {
    id: string;
    name: string;
    blend_mode: string;
    opacity: number;
    visible: boolean;
    locked: boolean;
    dataUrl: string;
    is_clipped?: boolean;
    layer_type?: import('@/types').LayerType;
  }[] = [];

  for (const layer of doc.layers) {
    const canvas = document.getElementById(`layer-canvas-${layer.id}`) as HTMLCanvasElement | null;
    if (!canvas) throw new Error(`Layer ${layer.name} is not ready to save`);
    const dataUrl = canvas.toDataURL('image/png');
    layerData.push({
      id: layer.id,
      name: layer.name,
      blend_mode: layer.blend_mode,
      opacity: layer.opacity,
      visible: layer.visible,
      locked: layer.locked,
      is_clipped: layer.is_clipped,
      layer_type: layer.layer_type,
      dataUrl,
    });
  }

  const projectPayload = {
    version: '1.0.0',
    app: 'CekcokDraw',
    exportedAt: new Date().toISOString(),
    document: {
      id: doc.id,
      title: doc.title,
      width: doc.width,
      height: doc.height,
      dpi: doc.dpi,
      active_layer_id: doc.active_layer_id,
      layers: layerData,
    },
  };

  const jsonString = JSON.stringify(projectPayload, null, 2);
  return new Blob([jsonString], { type: 'application/json' });
};

/**
 * Master multi-format exporter supporting PNG, JPEG, WebP, BMP, TIFF, SVG, PDF, and .cdraw
 */
export const compositeAndDownloadDocument = async (
  doc: DocumentInfo,
  options: ExportOptions
): Promise<void> => {
  const format = options.format;
  const quality = options.quality ?? 0.92;
  const filename = `${doc.title || 'artwork'}.${format === 'jpeg' ? 'jpg' : format}`;

  // 1. .cdraw Project Archive
  if (format === 'cdraw') {
    const blob = exportCekcokProject(doc);
    await downloadBlob(blob, filename);
    return;
  }

  if (format === 'psd') {
    const { exportPsd } = await import('./psd');
    await downloadBlob(await exportPsd(doc), filename);
    return;
  }
  const canvas = compositeVisibleLayersToCanvas(
    doc,
    !['jpeg', 'bmp', 'pdf'].includes(format) && options.transparentBg
  );

  if (format === 'bmp') {
    const blob = canvasToBmpBlob(canvas);
    await downloadBlob(blob, filename);
  } else if (format === 'svg') {
    const svgStr = canvasToSvgString(canvas, doc.title);
    const blob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
    await downloadBlob(blob, filename);
  } else if (format === 'pdf') {
    const blob = await canvasToPdfBlob(canvas, doc.dpi);
    await downloadBlob(blob, filename);
  } else if (format === 'tiff') {
    await downloadBlob(canvasToTiffBlob(canvas, doc.dpi), filename);
  } else {
    // PNG, JPEG, WebP
    const mime = format === 'png' ? 'image/png' : format === 'jpeg' ? 'image/jpeg' : 'image/webp';
    const blob = await canvasToBlob(canvas, mime, quality);
    await downloadBlob(blob, filename);
  }
};

const downloadBlob = async (blob: Blob, defaultFilename: string): Promise<void> => {
  if (bridge.isTauriEnvironment()) {
    try {
      const filePath = await save({
        defaultPath: defaultFilename,
      });
      if (filePath) {
        const buffer = await blob.arrayBuffer();
        await writeFile(filePath, new Uint8Array(buffer));
        return;
      } else {
        // User cancelled
        return;
      }
    } catch (err) {
      throw new Error(`Failed to save file: ${String(err)}`, { cause: err });
    }
  }

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.download = defaultFilename;
  link.href = url;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};
