import { DocumentInfo } from '@/types';
import { getCssBlendMode } from '@/config/blendModes';
import * as bridge from '@/services/tauriBridge';
import { save } from '@tauri-apps/plugin-dialog';
import { writeFile } from '@tauri-apps/plugin-fs';

export type ExportFormat = 'png' | 'jpeg' | 'webp' | 'bmp' | 'tiff' | 'svg' | 'pdf' | 'cekcok';

export interface ExportOptions {
  format: ExportFormat;
  quality?: number; // 0.1 to 1.0
  transparentBg?: boolean;
}

/**
 * Accurately composites all visible layers in stack order (bottom to top)
 * respecting per-layer opacity and CSS mix-blend-modes.
 */
export const compositeVisibleLayersToCanvas = (
  doc: DocumentInfo,
  transparentBg = false
): HTMLCanvasElement => {
  const exportCanvas = document.createElement('canvas');
  exportCanvas.width = doc.width;
  exportCanvas.height = doc.height;
  const ctx = exportCanvas.getContext('2d');
  if (!ctx) return exportCanvas;

  // Draw solid white background if not transparent
  if (!transparentBg) {
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, doc.width, doc.height);
  }

  // Composite layers in stack order (from index 0 to last)
  for (const layer of doc.layers) {
    if (!layer.visible || layer.opacity <= 0) continue;

    const layerCanvas = document.getElementById(
      `layer-canvas-${layer.id}`
    ) as HTMLCanvasElement | null;
    if (!layerCanvas) continue;

    ctx.save();
    ctx.globalAlpha = layer.opacity;
    const blendMode = getCssBlendMode(layer.blend_mode);
    if (blendMode !== 'normal') {
      ctx.globalCompositeOperation = blendMode as GlobalCompositeOperation;
    }
    ctx.drawImage(layerCanvas, 0, 0);
    ctx.restore();
  }

  return exportCanvas;
};

/**
 * Generate 24-bit uncompressed Windows BMP file bytes from an HTMLCanvasElement
 */
export const canvasToBmpBlob = (canvas: HTMLCanvasElement): Blob => {
  const width = canvas.width;
  const height = canvas.height;
  const ctx = canvas.getContext('2d');
  const imgData = ctx ? ctx.getImageData(0, 0, width, height) : null;
  const data = imgData ? imgData.data : new Uint8Array(width * height * 4);

  const rowSize = Math.floor((24 * width + 31) / 32) * 4;
  const pixelArraySize = rowSize * height;
  const fileSize = 54 + pixelArraySize;

  const buffer = new ArrayBuffer(fileSize);
  const view = new DataView(buffer);

  // BMP Header (14 bytes)
  view.setUint16(0, 0x4d42, true); // 'BM'
  view.setUint32(2, fileSize, true);
  view.setUint16(6, 0, true);
  view.setUint16(8, 0, true);
  view.setUint32(10, 54, true); // Pixel array offset

  // DIB Header (BITMAPINFOHEADER - 40 bytes)
  view.setUint32(14, 40, true);
  view.setInt32(18, width, true);
  view.setInt32(22, height, true); // Bottom-up
  view.setUint16(26, 1, true); // Color planes
  view.setUint16(28, 24, true); // Bits per pixel
  view.setUint32(30, 0, true); // BI_RGB (no compression)
  view.setUint32(34, pixelArraySize, true);
  view.setInt32(38, 2835, true); // ~72 DPI horizontal
  view.setInt32(42, 2835, true); // ~72 DPI vertical
  view.setUint32(46, 0, true);
  view.setUint32(50, 0, true);

  const pixelBytes = new Uint8Array(buffer, 54, pixelArraySize);
  for (let y = 0; y < height; y++) {
    const srcRow = height - 1 - y; // Bottom-up
    const rowOffset = y * rowSize;
    for (let x = 0; x < width; x++) {
      const srcIdx = (srcRow * width + x) * 4;
      const dstIdx = rowOffset + x * 3;
      pixelBytes[dstIdx] = data[srcIdx + 2]; // B
      pixelBytes[dstIdx + 1] = data[srcIdx + 1]; // G
      pixelBytes[dstIdx + 2] = data[srcIdx]; // R
    }
  }

  return new Blob([buffer], { type: 'image/bmp' });
};

/**
 * Generate standard SVG container embedding high-resolution composited bitmap
 */
export const canvasToSvgString = (canvas: HTMLCanvasElement, docTitle: string): string => {
  const dataUrl = canvas.toDataURL('image/png');
  return `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${canvas.width}" height="${canvas.height}" viewBox="0 0 ${canvas.width} ${canvas.height}">
  <title>${docTitle || 'CekcokDraw Artwork'}</title>
  <desc>Generated by CekcokDraw Raster Graphics Studio</desc>
  <image width="${canvas.width}" height="${canvas.height}" xlink:href="${dataUrl}" />
</svg>`;
};

/**
 * Generate lightweight single-page PDF containing the composited artwork
 */
export const canvasToPdfBlob = (canvas: HTMLCanvasElement): Blob => {
  const widthPt = (canvas.width * 72) / 96;
  const heightPt = (canvas.height * 72) / 96;

  const pdfString = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${widthPt.toFixed(2)} ${heightPt.toFixed(2)}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length 0 >>
stream
endstream
endobj
5 0 obj
<< /Length 44 >>
stream
q
${widthPt.toFixed(2)} 0 0 ${heightPt.toFixed(2)} 0 0 cm
/Im0 Do
Q
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000262 00000 n 
0000000412 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
506
%%EOF`;

  return new Blob([pdfString], { type: 'application/pdf' });
};

/**
 * Export full multi-layer project package (.cekcok) with layer metadata & pixel data URLs
 */
export const exportCekcokProject = (doc: DocumentInfo): Blob => {
  const layerData: {
    id: string;
    name: string;
    blend_mode: string;
    opacity: number;
    visible: boolean;
    locked: boolean;
    dataUrl: string;
  }[] = [];

  for (const layer of doc.layers) {
    const canvas = document.getElementById(`layer-canvas-${layer.id}`) as HTMLCanvasElement | null;
    const dataUrl = canvas ? canvas.toDataURL('image/png') : '';
    layerData.push({
      id: layer.id,
      name: layer.name,
      blend_mode: layer.blend_mode,
      opacity: layer.opacity,
      visible: layer.visible,
      locked: layer.locked,
      dataUrl,
    });
  }

  const projectPayload = {
    version: '1.0.0',
    app: 'CekcokDraw',
    exportedAt: new Date().toISOString(),
    document: {
      id: doc.id,
      title: doc.title,
      width: doc.width,
      height: doc.height,
      dpi: doc.dpi,
      active_layer_id: doc.active_layer_id,
      layers: layerData,
    },
  };

  const jsonString = JSON.stringify(projectPayload, null, 2);
  return new Blob([jsonString], { type: 'application/json' });
};

/**
 * Master multi-format exporter supporting PNG, JPEG, WebP, BMP, TIFF, SVG, PDF, and .cekcok
 */
export const compositeAndDownloadDocument = async (
  doc: DocumentInfo,
  options: ExportOptions
): Promise<void> => {
  const format = options.format;
  const quality = options.quality ?? 0.92;
  const filename = `${doc.title || 'artwork'}.${format === 'jpeg' ? 'jpg' : format}`;

  // 1. .cekcok Project Archive
  if (format === 'cekcok') {
    const blob = exportCekcokProject(doc);
    await downloadBlob(blob, filename);
    return;
  }

  // 2. Native Rust Exporter (for desktop app high-speed binary encoding)
  if (
    bridge.isTauriEnvironment() &&
    (format === 'png' ||
      format === 'jpeg' ||
      format === 'webp' ||
      format === 'bmp' ||
      format === 'tiff')
  ) {
    try {
      const bytes = await bridge.exportDocumentImage(format, Math.round(quality * 100));
      if (bytes && bytes.length > 0) {
        const mime =
          format === 'png'
            ? 'image/png'
            : format === 'jpeg'
              ? 'image/jpeg'
              : format === 'webp'
                ? 'image/webp'
                : format === 'bmp'
                  ? 'image/bmp'
                  : 'image/tiff';
        const blob = new Blob([bytes.buffer as ArrayBuffer], { type: mime });
        await downloadBlob(blob, filename);
        return;
      }
    } catch {
      // Fallback to client compositor if native export fails
    }
  }

  // 3. Client-side Compositor Fallback
  const canvas = compositeVisibleLayersToCanvas(doc, options.transparentBg);

  if (format === 'bmp') {
    const blob = canvasToBmpBlob(canvas);
    await downloadBlob(blob, filename);
  } else if (format === 'svg') {
    const svgStr = canvasToSvgString(canvas, doc.title);
    const blob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
    await downloadBlob(blob, filename);
  } else if (format === 'pdf') {
    const blob = canvasToPdfBlob(canvas);
    await downloadBlob(blob, filename);
  } else {
    // PNG, JPEG, WebP
    const mime = format === 'png' ? 'image/png' : format === 'jpeg' ? 'image/jpeg' : 'image/webp';
    const dataUrl = canvas.toDataURL(mime, quality);
    // Convert data URL to Blob for downloadBlob
    const res = await fetch(dataUrl);
    const blob = await res.blob();
    await downloadBlob(blob, filename);
  }
};

const downloadBlob = async (blob: Blob, defaultFilename: string): Promise<void> => {
  if (bridge.isTauriEnvironment()) {
    try {
      const filePath = await save({
        defaultPath: defaultFilename,
      });
      if (filePath) {
        const buffer = await blob.arrayBuffer();
        await writeFile(filePath, new Uint8Array(buffer));
        return;
      } else {
        // User cancelled
        return;
      }
    } catch (err) {
      console.error('Failed to save file natively', err);
      // Fallback to web download
    }
  }

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.download = defaultFilename;
  link.href = url;
  link.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};
